/**
 * @file 客户端与本地服务之间的共享协议入口。
 *
 * 本包是数据结构、事件格式与传输约定的唯一来源。
 */
export type {
  ActiveCompaction,
  AbortSessionResult,
  AgentRunStatus,
  AgentSessionState,
  AgentStreamEvent,
  AssistantSegmentStatus,
  CompactionReason,
  CreateSessionResult,
  EditResendResult,
  ForkSessionResult,
  PendingMessage,
  PendingMessagesChangedEvent,
  ProductAgentRun,
  ProductAssistantBlock,
  ProductAssistantSegmentItem,
  ProductCompactionItem,
  ProductExecutionPlanVisibilityItem,
  ProductHistoryDraft,
  ProductImageBlock,
  ProductRetryItem,
  ProductSessionHistory,
  ProductTextBlock,
  ProductThinkingBlock,
  ProductTimelineItem,
  ProductToolCallBlock,
  ProductToolDraft,
  ProductToolResultItem,
  ProductUserMessageItem,
  SessionExecutionPlan,
  SessionExecutionPlanStep,
  SessionExecutionPlanStepStatus,
  SessionArchivedEvent,
  SessionDeletedEvent,
  SessionHistoryChangedEvent,
  SessionDraftChangedEvent,
  SessionInfoChangedEvent,
  SessionModelChangedEvent,
  SessionSnapshotEvent,
  SessionUnavailableEvent,
  SessionSummary,
  TakePendingMessagesResult,
  ThinkingLevel,
  ThinkingLevelChangedEvent,
} from './chat.ts';
export { PRODUCT_HISTORY_SCHEMA_VERSION } from './chat.ts';
export type {
  AvailableModel,
  ProviderCredential,
  ModelSettings,
  ModelInfo,
  ModelReference,
  ProviderInfo,
  TestConnectionResult,
} from './model.ts';
export {
  assertRpcMethodParams,
  assertRpcMethodResult,
  isRpcMethod,
  parseRpcRequest,
  parseRpcServerMessage,
  RPC_PATH,
  RPC_PROTOCOL_VERSION,
  RPC_WEBSOCKET_SUBPROTOCOL,
  type InitializeParams,
  type InitializeResult,
  type RpcError,
  type RpcMethod,
  type RpcMethodParams,
  type RpcMethodResult,
  type RpcNotification,
  type RpcRequest,
  type RpcServerNotification,
  type RpcSuccess,
  RpcValidationError,
  type SessionEventParams,
  type SessionListEventParams,
  type SessionSubscribeParams,
  type SessionUnsubscribeParams,
} from './rpc.ts';
export {
  createForkSessionTitle,
  DEFAULT_SESSION_TITLE,
  resolveSessionTitle,
  type SessionTitleSources,
} from './session-title.ts';
export { DEFAULT_SERVICE_PORT, DEV_WEB_PORT, SERVICE_HOST } from './transport.ts';
